language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit
